version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-server-cqdg
    restart: on-failure
    environment:
      datasource.driver: "org.postgresql.Driver"
      datasource.url: "jdbc:postgresql://hapi-fhir-postgres-cqdg:5432/hapi"
      hibernate.dialect: "org.hibernate.dialect.PostgreSQL95Dialect"
      datasource.username: "admin"
      datasource.password: "admin"
    ports:
      - "8080:8080"
  hapi-fhir-postgres-cqdg:
    image: postgres:latest
    container_name: hapi-fhir-postgres-cqdg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'hapi'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - hapi-fhir-postgres-cqdg:/var/lib/postgresql/data
      - "./backup:/root/backup"
volumes:
  hapi-fhir-postgres-cqdg:
